
import React from 'react';
import { GitBranch, BrainCircuit, Zap, CheckCircle, ListChecks, PackageSearch, UserCheck, KeyRound } from 'lucide-react';
import { ASCII_COLORS } from '../constants';

interface InfoModalProps {
  show: boolean;
  onCancel: () => void;
}

const InfoSection: React.FC<{ title: string; icon: React.ReactNode; children: React.ReactNode }> = ({ title, icon, children }) => (
  <div className={`${ASCII_COLORS.inputBg} p-4 rounded-lg border ${ASCII_COLORS.border} border-opacity-70`}>
    <h3 className={`text-xl font-semibold mb-3 flex items-center ${ASCII_COLORS.accent}`}>
      {icon}
      {title}
    </h3>
    <div className={`space-y-2 text-sm ${ASCII_COLORS.text}`}>
      {children}
    </div>
  </div>
);

const ListItem: React.FC<{ children: React.ReactNode; type?: 'new' | 'fix' | 'improvement' | 'auth' }> = ({ children, type }) => {
  let icon = <Zap className="w-4 h-4 mr-2 text-yellow-400 shrink-0" />;
  if (type === 'new') icon = <Zap className="w-4 h-4 mr-2 text-green-400 shrink-0" />;
  if (type === 'fix') icon = <CheckCircle className="w-4 h-4 mr-2 text-blue-400 shrink-0" />;
  if (type === 'improvement') icon = <ListChecks className="w-4 h-4 mr-2 text-indigo-400 shrink-0" />;
  if (type === 'auth') icon = <UserCheck className="w-4 h-4 mr-2 text-pink-400 shrink-0" />;
  
  return <li className="flex items-start">{icon}{children}</li>;
};

const InfoModal: React.FC<InfoModalProps> = ({ show, onCancel }) => {
  if (!show) return null;

  return (
    <div className={`fixed inset-0 ${ASCII_COLORS.bg} bg-opacity-90 flex items-center justify-center p-4 z-50`}>
      <div className={`${ASCII_COLORS.modalBg} p-6 rounded-lg shadow-xl w-full max-w-4xl border-2 ${ASCII_COLORS.border} max-h-[90vh] flex flex-col`}>
        <h2 className={`text-3xl font-bold mb-6 ${ASCII_COLORS.accent} text-center border-b-2 ${ASCII_COLORS.border} pb-3`}>
          [ INVENTORY OS - System Archives ]
        </h2>
        <div className="overflow-y-auto pr-2 flex-grow custom-scrollbar">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <InfoSection title="Patch Notes (v2.6 - Current)" icon={<GitBranch className="mr-2"/>}>
              <ul className="space-y-3">
                <ListItem type="auth">**Google Sign-In Implemented:** Replaced anonymous authentication with Google Sign-In for user accounts.</ListItem>
                <ListItem type="fix">**Configuration Stability:** Correctly derives `APP_ID` from Firebase config, enhancing Firestore path stability. Explicitly handles optional fields to prevent `undefined` errors when saving items.</ListItem>
                <ListItem type="new">**Expanded AI Capabilities:** S.M.A.R.T.I.E. can now edit items, alongside creating/managing containers, checking stock, and finding expiring goods via function calling.</ListItem>
                <ListItem type="improvement">**AI Benchmark Test:** More robust benchmark sequence for testing AI's understanding and tool usage.</ListItem>
                <ListItem type="improvement">**UI/UX Enhancements:** Modals consistently close automatically on successful submissions. Improved Info Modal design.</ListItem>
                <ListItem type="fix">**Move to Bucket Logic:** Verified item removal from original location after successful move to bucket.</ListItem>
                <ListItem type="improvement">**API Key Guidance:** Added clearer console warnings for missing Gemini API Key environment variable.</ListItem>
              </ul>
              <p className="mt-4 text-xs opacity-80">Previous versions included anonymous auth, Firebase integration, core CRUD, and initial AI chat.</p>
            </InfoSection>

            <InfoSection title="Roadmap & Future Plans" icon={<BrainCircuit className="mr-2 w-6 h-6"/>}>
              <ul className="space-y-3">
                <ListItem><PackageSearch className="w-4 h-4 mr-2 text-teal-400 shrink-0" />**Advanced Search & Filtering:** Implement comprehensive client-side and potentially server-assisted search for items with complex filters (date ranges, price, etc.).</ListItem>
                <ListItem><Zap className="w-4 h-4 mr-2 text-rose-400 shrink-0" />**Vision AI:** Integrate image recognition (e.g., via Gemini Vision) for scanning receipts or identifying items from photos to quickly add them to inventory.</ListItem>
                <ListItem><ListChecks className="w-4 h-4 mr-2 text-sky-400 shrink-0" />**Shopping List Management:** Dedicated UI for viewing and managing the shopping list generated by AI or manually added.</ListItem>
                <ListItem><KeyRound className="w-4 h-4 mr-2 text-lime-400 shrink-0" />**Improved API Key Management:** Explore options for more secure client-side API key handling if feasible, or guidance for backend proxy setup for production.</ListItem>
                <ListItem><Zap className="w-4 h-4 mr-2 text-fuchsia-400 shrink-0" />**Notifications:** Detailed and configurable notifications for low stock, expiring items, etc.</ListItem>
                <ListItem><ListChecks className="w-4 h-4 mr-2 text-amber-400 shrink-0" />**Bulk Operations:** Allow users to select multiple items for batch actions like moving, deleting, or editing common properties.</ListItem>
                 <ListItem><UserCheck className="w-4 h-4 mr-2 text-purple-400 shrink-0" />**Inventory Sharing:** Allow users to share specific warehouses or their entire inventory with other registered users.</ListItem>
              </ul>
            </InfoSection>
          </div>
        </div>
        <div className="flex justify-center mt-6 pt-4 border-t border-gray-700">
          <button
            onClick={onCancel}
            className={`${ASCII_COLORS.buttonBg} ${ASCII_COLORS.accent} p-2 px-6 rounded-md ${ASCII_COLORS.buttonHoverBg} border ${ASCII_COLORS.border} text-lg`}
          >
            [ CLOSE ARCHIVES ]
          </button>
        </div>
      </div>
    </div>
  );
};

export default InfoModal;